# Generated by Django 5.2.4 on 2025-09-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goods', models.ManyToManyField(blank=True, help_text='Pick up to 2 products to display on the landing page.', related_name='featured_on_landing', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Landing configuration',
                'verbose_name_plural': 'Landing configuration',
            },
        ),
    ]
