# Generated by Django 5.2.5 on 2025-09-04 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_landingconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingThreeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], help_text='Position in the 3-items block (1..3)')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_products', to='catalog.landingconfig')),
                ('product', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='featured_in_three', to='catalog.product')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('config', 'position'), ('config', 'product')},
            },
        ),
    ]
